import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import * as XLSX from 'xlsx';
test('sample to reversible preview and both downloads without file network traffic',async({page})=>{
 const requests:string[]=[];page.on('request',r=>{if(r.method()==='POST')requests.push(r.url());});
 await page.goto('./');await page.getByRole('button',{name:'Try a sample spreadsheet'}).click();await expect(page.getByRole('heading',{name:'A little clarity for your data.'})).toBeVisible();
 await page.getByLabel('Remove exact duplicates').check();await page.getByLabel('Trim whitespace').check();await page.getByLabel('Remove empty rows').check();await page.getByRole('button',{name:'Preview changes'}).click();await expect(page.getByText('2 rows removed')).toBeVisible();
 for(const format of ['CSV','XLSX']){const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Download '+format,exact:true}).click();expect((await downloading).suggestedFilename()).toContain('-cleaned.');}
 await page.getByRole('button',{name:'Reset',exact:true}).click();await expect(page.getByRole('heading',{name:'03 Review & download'})).toHaveCount(0);await page.getByRole('button',{name:'Preview changes'}).click();await expect(page.getByText('0 rows removed')).toBeVisible();expect(requests).toEqual([]);
});
test('malformed CSV recovers and mobile has no horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('./');await page.getByLabel('Choose spreadsheet').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('A\n"oops')});await expect(page.locator('.feedback[role=alert]')).toContainText('Malformed CSV');await page.getByRole('button',{name:'Try a sample spreadsheet'}).click();await expect(page.getByText('sample-customers.csv')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
test('formula workbook is analysis only',async({page})=>{await page.goto('./');await page.getByLabel('Choose spreadsheet').setInputFiles('tests/fixtures/formulas.xlsx');await expect(page.getByText('Formulas detected:',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Preview changes'})).toBeDisabled();await expect(page.getByRole('button',{name:'Download XLSX'})).toHaveCount(0);});
test('multi-sheet export requires acknowledgement and retains other sheet values',async({page})=>{
 await page.goto('./');await page.getByLabel('Choose spreadsheet').setInputFiles('tests/fixtures/multi-sheet.xlsx');await expect(page.getByLabel('Worksheet')).toBeVisible();await expect(page.getByLabel('Worksheet').locator('option')).toHaveCount(2);
 await page.getByLabel('Trim whitespace').check();await page.getByLabel('Remove exact duplicates').check();await page.getByRole('button',{name:'Preview changes'}).click();await expect(page.getByRole('button',{name:'Download XLSX'})).toBeDisabled();await page.getByLabel('I understand this is a data-only export').check();
 const promise=page.waitForEvent('download');await page.getByRole('button',{name:'Download XLSX'}).click();const downloaded=await promise;const wb=XLSX.read(fs.readFileSync((await downloaded.path())!),{type:'buffer'});expect(wb.SheetNames).toEqual(['Customers','Regions']);expect(wb.Sheets.Customers.A2.v).toBe('Zoë');expect(wb.Sheets.Customers.B2.v).toBe('0012');expect(wb.Sheets.Regions.A3.v).toBe('東京');expect(wb.Sheets.Customers['!ref']).toBe('A1:B2');
 await page.getByLabel('Worksheet').selectOption('1');await expect(page.getByLabel('Trim whitespace')).not.toBeChecked();await expect(page.getByRole('button',{name:'Download XLSX'})).toHaveCount(0);
});
test('keyboard access, dark mode, privacy and responsive screenshots',async({page})=>{await page.goto('./');await page.getByRole('button',{name:'Switch to dark theme'}).click();await expect(page.locator('.app')).toHaveClass('app dark');await page.screenshot({path:'test-results/home-dark.png',fullPage:true});await page.getByRole('button',{name:'Switch to light theme'}).click();await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/home-mobile.png',fullPage:true});await page.getByRole('link',{name:'Privacy',exact:true}).click();await expect(page.getByRole('heading',{name:'Your data stays yours.'})).toBeVisible();});
